-- Lesson 2: 初始化核心资产表 (2026-01-18)
-- 作用：创建 assets 表并插入演示数据

-- 1. 创建表结构
create table public.assets (
  id bigint generated by default as identity primary key,
  name text not null,
  type text null,
  expiry_date date null,
  has_project boolean null default false
);

-- 2. 插入 Lesson 2 的演示数据
insert into public.assets (name, type, expiry_date, has_project)
values
  ('关于采用AI将鸡毛组成羊毛分子结构', '专利', '2026-01-21', false),
  ('区块链技术实现环卫两费征收', '软著', '2026-01-19', false);